import { CompanySeed, makeThreeTs } from "./company-factory";

const b = (
  gtm: number,
  fund: number,
  regional: number,
  quota: number,
  pmf: number
) => ({
  gtmMomentum: gtm,
  fundingVelocity: fund,
  regionalBalance: regional,
  quotaReality: quota,
  pmfStrength: pmf,
});

export const forbesAi50Seeds: CompanySeed[] = [
  {
    slug: "openai",
    name: "OpenAI",
    website: "https://openai.com",
    description: "AI model developer behind ChatGPT, GPT-4, and enterprise AI APIs.",
    industry: "AI / Foundation Models",
    stage: "Series F ($300B val)",
    headcount: "3,500+",
    hq: "San Francisco, CA",
    founded: 2015,
    sellsItself:
      "ChatGPT Enterprise demand is pulling reps — inbound from every Fortune 500 CIO evaluating AI strategy.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(95, 98, 82, 72, 94),
    threeTs: makeThreeTs(96, 88, 78, {
      timing: "Enterprise AI adoption inflection — every company buying",
      territory: "Global expansion with dedicated enterprise pods",
      talent: "Competitive but quota achievable on consumption expansion",
    }),
    financials: {
      score: 98,
      revenue: "$13B+ ARR (est.)",
      funding: "$40B Series F",
      runway: "Well-funded",
      growthRate: "120% YoY",
      lastRound: "Series F (2025)",
      investors: ["Microsoft", "Thrive Capital", "SoftBank"],
    },
    pmf: {
      score: 96,
      nps: 72,
      retention: "140%+ net expansion",
      marketGrowth: "Enterprise AI spend growing 45% CAGR",
      competitivePosition: "Category leader",
      signals: ["ChatGPT Enterprise", "API consumption model", "Fortune 500 logos"],
    },
    packages: {
      score: 90,
      baseSalary: "$150K–$200K",
      ote: "$300K–$450K",
      equity: "Significant equity grants",
      benefits: ["Full benefits", "AI compute credits"],
      quota: "$2M–$5M consumption",
      quotaAttainment: "72% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE", "Solutions Architect"],
    gtmTeamSize: "400+",
    expandingRegions: ["EMEA", "APAC", "US Enterprise"],
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    website: "https://anthropic.com",
    description: "AI safety company building Claude models for enterprise and developers.",
    industry: "AI / Foundation Models",
    stage: "Series E ($61.5B val)",
    headcount: "1,500+",
    hq: "San Francisco, CA",
    founded: 2021,
    sellsItself:
      "Claude Enterprise winning regulated industries — reps ride safety-first positioning vs OpenAI.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(92, 95, 80, 75, 93),
    threeTs: makeThreeTs(94, 85, 80, {
      timing: "Enterprise AI with safety/compliance moat",
      territory: "Financial services and healthcare greenfield",
      talent: "Strong comp, growing enablement org",
    }),
    financials: {
      score: 95,
      revenue: "$2B+ ARR (est.)",
      funding: "$3.5B Series E",
      runway: "Well-funded",
      growthRate: "150% YoY",
      lastRound: "Series E (2025)",
      investors: ["Google", "Spark Capital", "Salesforce Ventures"],
    },
    pmf: {
      score: 94,
      nps: 68,
      retention: "135%+ net expansion",
      marketGrowth: "Enterprise AI spend growing 45% CAGR",
      competitivePosition: "Strong #2",
      signals: ["Claude Enterprise", "AWS/Google partnerships", "Regulated industry wins"],
    },
    packages: {
      score: 88,
      baseSalary: "$140K–$190K",
      ote: "$280K–$400K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$1.5M–$4M consumption",
      quotaAttainment: "75% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Solutions Engineer", "Account Executive"],
    gtmTeamSize: "200+",
    expandingRegions: ["EMEA", "US Enterprise"],
  },
  {
    slug: "cursor",
    name: "Cursor (Anysphere)",
    website: "https://cursor.com",
    description: "AI-powered code editor helping engineers write and ship software faster.",
    industry: "AI / Developer Tools",
    stage: "Series C ($9.9B val)",
    headcount: "150+",
    hq: "San Francisco, CA",
    founded: 2022,
    sellsItself:
      "Fastest-growing dev tool in history — product-led growth with enterprise upsell motion heating up.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "booking",
    benchmarks: b(97, 96, 75, 82, 95),
    threeTs: makeThreeTs(98, 82, 85, {
      timing: "AI coding tools at inflection — every eng org evaluating",
      territory: "PLG funnel feeding enterprise expansion",
      talent: "Early GTM org means greenfield quota",
    }),
    financials: {
      score: 96,
      revenue: "$500M+ ARR",
      funding: "$900M Series C",
      runway: "Well-funded",
      growthRate: "300%+ YoY",
      lastRound: "Series C (2025)",
      investors: ["Thrive Capital", "a16z", "Accel"],
    },
    pmf: {
      score: 96,
      nps: 78,
      retention: "150%+ net expansion",
      marketGrowth: "AI dev tools growing 60% CAGR",
      competitivePosition: "Category leader",
      signals: ["$500M ARR in 3 years", "Viral adoption", "Enterprise tier launch"],
    },
    packages: {
      score: 85,
      baseSalary: "$120K–$160K",
      ote: "$240K–$320K",
      equity: "Early-stage equity upside",
      benefits: ["Full benefits"],
      quota: "$500K–$1.5M ARR",
      quotaAttainment: "82% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE", "SDR"],
    gtmTeamSize: "50+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "databricks",
    name: "Databricks",
    website: "https://databricks.com",
    description: "Unified data and AI platform for lakehouse architecture and ML workloads.",
    industry: "Data / AI Infrastructure",
    stage: "Series I ($62B val)",
    headcount: "7,000+",
    hq: "San Francisco, CA",
    founded: 2013,
    sellsItself:
      "Consumption model means AEs expand accounts as data workloads grow — land-and-expand on steroids.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(88, 94, 85, 70, 92),
    threeTs: makeThreeTs(90, 88, 75, {
      timing: "Data + AI convergence driving platform consolidation",
      territory: "Global enterprise with strong partner ecosystem",
      talent: "Mature GTM but consumption comp rewards expansion",
    }),
    financials: {
      score: 94,
      revenue: "$3B+ ARR",
      funding: "$10B Series I",
      runway: "Well-funded",
      growthRate: "50% YoY",
      lastRound: "Series I (2024)",
      investors: ["a16z", "NEA", "Microsoft"],
    },
    pmf: {
      score: 93,
      nps: 65,
      retention: "140%+ net expansion",
      marketGrowth: "Data platform market growing 22% CAGR",
      competitivePosition: "Category leader",
      signals: ["Lakehouse architecture", "AI/ML workloads", "Consumption growth"],
    },
    packages: {
      score: 86,
      baseSalary: "$130K–$175K",
      ote: "$260K–$350K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits", "RSUs"],
      quota: "$1M–$3M consumption",
      quotaAttainment: "70% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE", "Solutions Architect"],
    gtmTeamSize: "1,500+",
    expandingRegions: ["APAC", "EMEA", "LATAM", "US Enterprise"],
  },
  {
    slug: "harvey",
    name: "Harvey",
    website: "https://harvey.ai",
    description: "AI platform automating legal workflows for law firms and legal teams.",
    industry: "AI / Legal Tech",
    stage: "Series C ($3B val)",
    headcount: "300+",
    hq: "San Francisco, CA",
    founded: 2022,
    sellsItself:
      "AmLaw 100 adoption creating reference selling — legal AI is the hottest vertical in enterprise.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(90, 92, 78, 80, 91),
    threeTs: makeThreeTs(93, 80, 82, {
      timing: "Legal AI adoption accelerating across BigLaw",
      territory: "Expanding from AmLaw 100 to mid-market",
      talent: "Early GTM team with strong logos to sell into",
    }),
    financials: {
      score: 90,
      revenue: "$100M+ ARR (est.)",
      funding: "$300M Series C",
      runway: "Well-funded",
      growthRate: "200% YoY",
      lastRound: "Series C (2025)",
      investors: ["Sequoia", "OpenAI", "Kleiner Perkins"],
    },
    pmf: {
      score: 92,
      nps: 70,
      retention: "130%+ net expansion",
      marketGrowth: "Legal AI market growing 35% CAGR",
      competitivePosition: "Category leader",
      signals: ["AmLaw 100 adoption", "Workflow automation", "Document review"],
    },
    packages: {
      score: 84,
      baseSalary: "$130K–$170K",
      ote: "$260K–$340K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$800K–$1.5M ARR",
      quotaAttainment: "80% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Account Executive", "Solutions Consultant"],
    gtmTeamSize: "80+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "glean",
    name: "Glean",
    website: "https://glean.com",
    description: "Enterprise AI search and knowledge management across workplace apps.",
    industry: "AI / Enterprise Search",
    stage: "Series D ($4.6B val)",
    headcount: "600+",
    hq: "Palo Alto, CA",
    founded: 2019,
    sellsItself:
      "Every enterprise has a knowledge problem — Glean's AI search sells itself in demos.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(86, 88, 82, 76, 89),
    threeTs: makeThreeTs(88, 84, 78, {
      timing: "Enterprise AI search becoming must-have",
      territory: "Strong enterprise motion with global expansion",
      talent: "Growing GTM org with ex-Google/Meta sellers",
    }),
    financials: {
      score: 88,
      revenue: "$100M+ ARR",
      funding: "$600M+ total",
      runway: "Well-funded",
      growthRate: "80% YoY",
      lastRound: "Series D (2024)",
      investors: ["Sequoia", "Lightspeed", "General Catalyst"],
    },
    pmf: {
      score: 90,
      nps: 62,
      retention: "125%+ net expansion",
      marketGrowth: "Enterprise search growing 25% CAGR",
      competitivePosition: "Category leader",
      signals: ["Enterprise search", "AI assistants", "Knowledge graph"],
    },
    packages: {
      score: 82,
      baseSalary: "$125K–$165K",
      ote: "$250K–$330K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits"],
      quota: "$700K–$1.2M ARR",
      quotaAttainment: "76% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE", "SDR"],
    gtmTeamSize: "150+",
    expandingRegions: ["US Enterprise", "EMEA", "APAC"],
  },
  {
    slug: "sierra",
    name: "Sierra",
    website: "https://sierra.ai",
    description: "AI-powered customer service agents for enterprise brands.",
    industry: "AI / Customer Service",
    stage: "Series B ($4.5B val)",
    headcount: "200+",
    hq: "San Francisco, CA",
    founded: 2023,
    sellsItself:
      "Bret Taylor pedigree + AI agent demos that close themselves — hottest CS automation play.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(91, 90, 72, 85, 90),
    threeTs: makeThreeTs(94, 78, 88, {
      timing: "AI agents replacing BPO — massive TAM shift",
      territory: "Early GTM with Fortune 500 logos",
      talent: "Small team, greenfield quota, ex-Salesforce leadership",
    }),
    financials: {
      score: 92,
      revenue: "$50M+ ARR (est.)",
      funding: "$175M Series B",
      runway: "Well-funded",
      growthRate: "250% YoY",
      lastRound: "Series B (2025)",
      investors: ["Sequoia", "Benchmark", "ICONIQ"],
    },
    pmf: {
      score: 91,
      nps: 72,
      retention: "140%+ net expansion",
      marketGrowth: "AI customer service growing 40% CAGR",
      competitivePosition: "Emerging leader",
      signals: ["AI agents", "Enterprise brands", "Bret Taylor founding team"],
    },
    packages: {
      score: 86,
      baseSalary: "$135K–$175K",
      ote: "$270K–$350K",
      equity: "Significant early equity",
      benefits: ["Full benefits"],
      quota: "$600K–$1M ARR",
      quotaAttainment: "85% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Account Executive"],
    gtmTeamSize: "40+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "mistral-ai",
    name: "Mistral AI",
    website: "https://mistral.ai",
    description: "European AI lab building open and enterprise-grade language models.",
    industry: "AI / Foundation Models",
    stage: "Series C (€5.8B val)",
    headcount: "300+",
    hq: "Paris, France",
    founded: 2023,
    sellsItself:
      "European AI sovereignty play — enterprise and government buyers want an alternative to US models.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(85, 90, 88, 70, 87),
    threeTs: makeThreeTs(88, 86, 72, {
      timing: "EU AI regulation creating demand for sovereign models",
      territory: "Strong EMEA position, expanding to US",
      talent: "European comp lower but equity upside significant",
    }),
    financials: {
      score: 88,
      revenue: "$100M+ ARR (est.)",
      funding: "€600M Series C",
      runway: "Well-funded",
      growthRate: "180% YoY",
      lastRound: "Series C (2025)",
      investors: ["General Catalyst", "a16z", "Lightspeed"],
    },
    pmf: {
      score: 88,
      nps: 60,
      retention: "120%+ net expansion",
      marketGrowth: "European AI market growing 50% CAGR",
      competitivePosition: "European leader",
      signals: ["Open models", "EU sovereignty", "Enterprise API"],
    },
    packages: {
      score: 78,
      baseSalary: "€80K–€120K",
      ote: "€160K–€240K",
      equity: "Significant equity",
      benefits: ["EU benefits"],
      quota: "€500K–€1M consumption",
      quotaAttainment: "70% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Solutions Engineer"],
    gtmTeamSize: "60+",
    expandingRegions: ["EMEA", "US Enterprise"],
  },
  {
    slug: "scale-ai",
    name: "Scale AI",
    website: "https://scale.com",
    description: "Data labeling and AI infrastructure for training enterprise models.",
    industry: "AI / Data Infrastructure",
    stage: "Series F ($14B val)",
    headcount: "900+",
    hq: "San Francisco, CA",
    founded: 2016,
    sellsItself:
      "Every AI model needs training data — Scale is the picks-and-shovels play with government contracts.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(75, 88, 70, 65, 85),
    threeTs: makeThreeTs(82, 72, 68, {
      timing: "AI training data demand still strong but Meta deal shifts trajectory",
      territory: "Government and enterprise — some international contraction",
      talent: "Leadership changes create uncertainty for new reps",
    }),
    financials: {
      score: 86,
      revenue: "$1B+ ARR (est.)",
      funding: "$14.3B Meta investment",
      runway: "Well-funded",
      growthRate: "40% YoY",
      lastRound: "Meta strategic (2025)",
      investors: ["Meta", "Accel", "Index Ventures"],
    },
    pmf: {
      score: 86,
      nps: 55,
      retention: "115% net expansion",
      marketGrowth: "AI data market growing 30% CAGR",
      competitivePosition: "Category leader",
      signals: ["Government contracts", "Enterprise data", "Meta partnership"],
    },
    packages: {
      score: 80,
      baseSalary: "$130K–$170K",
      ote: "$260K–$340K",
      equity: "Equity (restructuring)",
      benefits: ["Full benefits"],
      quota: "$800K–$1.5M ARR",
      quotaAttainment: "65% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Federal AE", "Solutions Engineer"],
    gtmTeamSize: "200+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    website: "https://perplexity.ai",
    description: "AI-powered answer engine challenging traditional search.",
    industry: "AI / Search",
    stage: "Series C ($9B val)",
    headcount: "250+",
    hq: "San Francisco, CA",
    founded: 2022,
    sellsItself:
      "Enterprise search API gaining traction — consumption model with viral consumer funnel.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(88, 92, 70, 78, 88),
    threeTs: makeThreeTs(90, 75, 80, {
      timing: "AI search disrupting Google — enterprise API emerging",
      territory: "Consumer PLG feeding enterprise — early international",
      talent: "Small GTM team, greenfield opportunity",
    }),
    financials: {
      score: 90,
      revenue: "$100M+ ARR (est.)",
      funding: "$500M+ total",
      runway: "Well-funded",
      growthRate: "200% YoY",
      lastRound: "Series C (2024)",
      investors: ["IVP", "NEA", "Nvidia"],
    },
    pmf: {
      score: 89,
      nps: 65,
      retention: "125%+ net expansion",
      marketGrowth: "AI search growing 50% CAGR",
      competitivePosition: "Emerging leader",
      signals: ["Consumer adoption", "Enterprise API", "Pro subscriptions"],
    },
    packages: {
      score: 82,
      baseSalary: "$120K–$160K",
      ote: "$240K–$320K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$500K–$1M consumption",
      quotaAttainment: "78% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE"],
    gtmTeamSize: "30+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "cohere",
    name: "Cohere",
    website: "https://cohere.com",
    description: "Enterprise AI platform for building and deploying language models.",
    industry: "AI / Foundation Models",
    stage: "Series D ($5.5B val)",
    headcount: "400+",
    hq: "Toronto, Canada",
    founded: 2019,
    sellsItself:
      "Enterprise-first AI with data privacy focus — strong in regulated industries and Canada/EU.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(82, 85, 80, 72, 86),
    threeTs: makeThreeTs(85, 82, 74, {
      timing: "Enterprise AI with privacy-first positioning",
      territory: "Canada/EU stronghold expanding to US enterprise",
      talent: "Growing GTM with competitive comp",
    }),
    financials: {
      score: 84,
      revenue: "$100M+ ARR (est.)",
      funding: "$500M+ total",
      runway: "Well-funded",
      growthRate: "100% YoY",
      lastRound: "Series D (2024)",
      investors: ["Nvidia", "Oracle", "Salesforce Ventures"],
    },
    pmf: {
      score: 86,
      nps: 58,
      retention: "120%+ net expansion",
      marketGrowth: "Enterprise AI growing 45% CAGR",
      competitivePosition: "Strong challenger",
      signals: ["Enterprise focus", "Data privacy", "RAG capabilities"],
    },
    packages: {
      score: 80,
      baseSalary: "$120K–$160K",
      ote: "$240K–$320K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits"],
      quota: "$600K–$1.2M consumption",
      quotaAttainment: "72% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Solutions Engineer"],
    gtmTeamSize: "80+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "runway",
    name: "Runway",
    website: "https://runwayml.com",
    description: "AI video and image generation for creative professionals and enterprises.",
    industry: "AI / Creative Tools",
    stage: "Series D ($3B val)",
    headcount: "200+",
    hq: "New York, NY",
    founded: 2018,
    sellsItself:
      "Hollywood and enterprise creative teams adopting AI video — visual demos sell themselves.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(84, 86, 72, 75, 88),
    threeTs: makeThreeTs(88, 76, 78, {
      timing: "AI video generation hitting mainstream adoption",
      territory: "Creative industry + enterprise marketing teams",
      talent: "PLG funnel with emerging enterprise motion",
    }),
    financials: {
      score: 86,
      revenue: "$80M+ ARR (est.)",
      funding: "$545M total",
      runway: "Well-funded",
      growthRate: "120% YoY",
      lastRound: "Series D (2024)",
      investors: ["Google", "Nvidia", "Felix Capital"],
    },
    pmf: {
      score: 90,
      nps: 68,
      retention: "130%+ net expansion",
      marketGrowth: "AI creative tools growing 40% CAGR",
      competitivePosition: "Category leader",
      signals: ["Gen-3 video model", "Hollywood adoption", "Enterprise API"],
    },
    packages: {
      score: 78,
      baseSalary: "$110K–$150K",
      ote: "$220K–$300K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$400K–$800K consumption",
      quotaAttainment: "75% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Creative Partnerships"],
    gtmTeamSize: "40+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    website: "https://elevenlabs.io",
    description: "AI voice generation and cloning for content creators and enterprises.",
    industry: "AI / Voice",
    stage: "Series C ($3.3B val)",
    headcount: "200+",
    hq: "New York, NY",
    founded: 2022,
    sellsItself:
      "Voice AI is the next frontier — enterprise dubbing and accessibility use cases exploding.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(86, 88, 75, 78, 87),
    threeTs: makeThreeTs(89, 78, 80, {
      timing: "Voice AI adoption across media and enterprise",
      territory: "PLG with enterprise upsell in media/entertainment",
      talent: "Early GTM, greenfield quota",
    }),
    financials: {
      score: 86,
      revenue: "$100M+ ARR (est.)",
      funding: "$281M total",
      runway: "Well-funded",
      growthRate: "150% YoY",
      lastRound: "Series C (2025)",
      investors: ["a16z", "Sequoia", "NEA"],
    },
    pmf: {
      score: 88,
      nps: 70,
      retention: "135%+ net expansion",
      marketGrowth: "Voice AI market growing 35% CAGR",
      competitivePosition: "Category leader",
      signals: ["Voice cloning", "Enterprise dubbing", "API platform"],
    },
    packages: {
      score: 80,
      baseSalary: "$115K–$155K",
      ote: "$230K–$310K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$400K–$800K consumption",
      quotaAttainment: "78% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE"],
    gtmTeamSize: "35+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "writer",
    name: "Writer",
    website: "https://writer.com",
    description: "Enterprise AI platform for content generation and knowledge work.",
    industry: "AI / Enterprise Software",
    stage: "Series C ($1.9B val)",
    headcount: "300+",
    hq: "San Francisco, CA",
    founded: 2020,
    sellsItself:
      "Full-stack enterprise AI with custom models — Palantir-style land-and-expand in Fortune 500.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(83, 84, 78, 74, 85),
    threeTs: makeThreeTs(86, 80, 76, {
      timing: "Enterprise AI content tools gaining budget",
      territory: "Fortune 500 focus with industry verticals",
      talent: "Mature enterprise sales culture",
    }),
    financials: {
      score: 84,
      revenue: "$80M+ ARR (est.)",
      funding: "$326M total",
      runway: "Well-funded",
      growthRate: "80% YoY",
      lastRound: "Series C (2024)",
      investors: ["Iconiq", "Insight Partners", "Balderton"],
    },
    pmf: {
      score: 86,
      nps: 58,
      retention: "120%+ net expansion",
      marketGrowth: "Enterprise AI content growing 30% CAGR",
      competitivePosition: "Strong challenger",
      signals: ["Custom models", "Enterprise governance", "Knowledge graphs"],
    },
    packages: {
      score: 80,
      baseSalary: "$125K–$165K",
      ote: "$250K–$330K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits"],
      quota: "$600K–$1M ARR",
      quotaAttainment: "74% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Industry AE"],
    gtmTeamSize: "80+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "abridge",
    name: "Abridge",
    website: "https://abridge.com",
    description: "AI-powered medical conversation documentation for healthcare providers.",
    industry: "AI / Healthcare",
    stage: "Series D ($2.75B val)",
    headcount: "250+",
    hq: "San Francisco, CA",
    founded: 2018,
    sellsItself:
      "Healthcare AI with clear ROI — doctors save 2+ hours/day, hospital systems buy fast.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "booking",
    benchmarks: b(87, 90, 75, 82, 92),
    threeTs: makeThreeTs(91, 78, 84, {
      timing: "Healthcare AI documentation mandate accelerating",
      territory: "Hospital system deals with long cycles but huge ACV",
      talent: "Healthcare sales experience highly valued",
    }),
    financials: {
      score: 90,
      revenue: "$80M+ ARR (est.)",
      funding: "$458M total",
      runway: "Well-funded",
      growthRate: "150% YoY",
      lastRound: "Series D (2025)",
      investors: ["a16z", "Khosla Ventures", "IVP"],
    },
    pmf: {
      score: 93,
      nps: 72,
      retention: "140%+ net expansion",
      marketGrowth: "Healthcare AI growing 35% CAGR",
      competitivePosition: "Category leader",
      signals: ["Hospital adoption", "Epic integration", "Physician time savings"],
    },
    packages: {
      score: 84,
      baseSalary: "$130K–$170K",
      ote: "$260K–$340K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$700K–$1.2M ARR",
      quotaAttainment: "82% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Healthcare AE"],
    gtmTeamSize: "60+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "deepl",
    name: "DeepL",
    website: "https://deepl.com",
    description: "AI-powered language translation for businesses and developers.",
    industry: "AI / Translation",
    stage: "Series C ($2B val)",
    headcount: "900+",
    hq: "Cologne, Germany",
    founded: 2017,
    sellsItself:
      "Best-in-class translation quality — enterprise API with consumption-based expansion.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(80, 82, 88, 76, 88),
    threeTs: makeThreeTs(84, 86, 74, {
      timing: "Globalization + AI translation demand steady",
      territory: "Strong EMEA, expanding US enterprise",
      talent: "European HQ with growing US sales team",
    }),
    financials: {
      score: 84,
      revenue: "$100M+ ARR",
      funding: "$420M total",
      runway: "Profitable trajectory",
      growthRate: "60% YoY",
      lastRound: "Series C (2024)",
      investors: ["Index Ventures", "Benchmark", "IVP"],
    },
    pmf: {
      score: 90,
      nps: 75,
      retention: "125%+ net expansion",
      marketGrowth: "AI translation growing 20% CAGR",
      competitivePosition: "Quality leader",
      signals: ["Superior quality", "Enterprise API", "Global customer base"],
    },
    packages: {
      score: 78,
      baseSalary: "€70K–€110K",
      ote: "€140K–€220K",
      equity: "Pre-IPO equity",
      benefits: ["EU benefits"],
      quota: "€400K–€800K consumption",
      quotaAttainment: "76% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE"],
    gtmTeamSize: "100+",
    expandingRegions: ["EMEA", "US Enterprise", "APAC"],
  },
  {
    slug: "hugging-face",
    name: "Hugging Face",
    website: "https://huggingface.co",
    description: "Open-source AI platform and model hub for ML developers and enterprises.",
    industry: "AI / ML Platform",
    stage: "Series D ($4.5B val)",
    headcount: "250+",
    hq: "New York, NY",
    founded: 2016,
    sellsItself:
      "The GitHub of AI — developer community creates enterprise pipeline for inference and fine-tuning.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(82, 85, 75, 72, 90),
    threeTs: makeThreeTs(86, 76, 74, {
      timing: "Open-source AI adoption accelerating in enterprise",
      territory: "Developer community feeding enterprise deals",
      talent: "Technical sales role — ML knowledge required",
    }),
    financials: {
      score: 86,
      revenue: "$80M+ ARR (est.)",
      funding: "$395M total",
      runway: "Well-funded",
      growthRate: "100% YoY",
      lastRound: "Series D (2024)",
      investors: ["Google", "Amazon", "Nvidia", "Salesforce"],
    },
    pmf: {
      score: 92,
      nps: 72,
      retention: "130%+ net expansion",
      marketGrowth: "ML platform market growing 30% CAGR",
      competitivePosition: "Community leader",
      signals: ["500K+ models", "Enterprise inference", "Open source"],
    },
    packages: {
      score: 78,
      baseSalary: "$120K–$160K",
      ote: "$240K–$320K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits"],
      quota: "$400K–$800K consumption",
      quotaAttainment: "72% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Developer Advocate"],
    gtmTeamSize: "40+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
  {
    slug: "together-ai",
    name: "Together AI",
    website: "https://together.ai",
    description: "AI cloud platform for running and fine-tuning open-source models.",
    industry: "AI / Cloud Infrastructure",
    stage: "Series B ($3.3B val)",
    headcount: "200+",
    hq: "San Francisco, CA",
    founded: 2022,
    sellsItself:
      "Cheaper alternative to OpenAI API — consumption model with developer-first adoption.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(85, 88, 70, 76, 86),
    threeTs: makeThreeTs(88, 74, 78, {
      timing: "AI inference cost optimization driving adoption",
      territory: "Developer PLG with enterprise upsell emerging",
      talent: "Technical sales, early GTM org",
    }),
    financials: {
      score: 86,
      revenue: "$100M+ ARR (est.)",
      funding: "$534M total",
      runway: "Well-funded",
      growthRate: "150% YoY",
      lastRound: "Series B (2025)",
      investors: ["Kleiner Perkins", "Nvidia", "Emergence"],
    },
    pmf: {
      score: 87,
      nps: 62,
      retention: "130%+ net expansion",
      marketGrowth: "AI inference market growing 50% CAGR",
      competitivePosition: "Cost leader",
      signals: ["Open model hosting", "Fine-tuning", "Cost advantage"],
    },
    packages: {
      score: 80,
      baseSalary: "$120K–$160K",
      ote: "$240K–$320K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$500K–$1M consumption",
      quotaAttainment: "76% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Solutions Engineer"],
    gtmTeamSize: "35+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "speak",
    name: "Speak",
    website: "https://speak.com",
    description: "AI-powered language learning app with 10M+ users.",
    industry: "AI / EdTech",
    stage: "Series C ($1B val)",
    headcount: "150+",
    hq: "San Francisco, CA",
    founded: 2016,
    sellsItself:
      "Consumer app with B2B enterprise language training emerging — viral product-led growth.",
    categories: ["forbes_ai50"],
    salesMotion: "hybrid",
    compModel: "booking",
    benchmarks: b(84, 86, 68, 80, 89),
    threeTs: makeThreeTs(87, 72, 82, {
      timing: "AI language learning at consumer scale",
      territory: "B2B enterprise training nascent but growing",
      talent: "Early B2B GTM — greenfield for enterprise sellers",
    }),
    financials: {
      score: 84,
      revenue: "$50M+ ARR (est.)",
      funding: "$162M total",
      runway: "Well-funded",
      growthRate: "120% YoY",
      lastRound: "Series C (2025)",
      investors: ["OpenAI Startup Fund", "Founders Fund", "Y Combinator"],
    },
    pmf: {
      score: 91,
      nps: 78,
      retention: "140%+ consumer retention",
      marketGrowth: "AI EdTech growing 25% CAGR",
      competitivePosition: "Category leader",
      signals: ["10M+ users", "AI tutor", "Enterprise B2B launch"],
    },
    packages: {
      score: 78,
      baseSalary: "$100K–$140K",
      ote: "$200K–$280K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$300K–$600K ARR",
      quotaAttainment: "80% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Mid-Market AE"],
    gtmTeamSize: "20+",
    expandingRegions: ["US Mid-Market"],
  },
  {
    slug: "xai",
    name: "xAI",
    website: "https://x.ai",
    description: "Elon Musk's AI company building Grok models and AI infrastructure.",
    industry: "AI / Foundation Models",
    stage: "Series C ($50B val)",
    headcount: "500+",
    hq: "San Francisco, CA",
    founded: 2023,
    sellsItself:
      "Massive compute advantage via X/Twitter data — enterprise API emerging with aggressive pricing.",
    categories: ["forbes_ai50"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(88, 94, 65, 68, 82),
    threeTs: makeThreeTs(90, 68, 70, {
      timing: "AI model race with unique data advantage",
      territory: "Early enterprise GTM, X ecosystem integration",
      talent: "High-risk/high-reward — leadership volatility",
    }),
    financials: {
      score: 92,
      revenue: "$500M+ ARR (est.)",
      funding: "$12.1B total",
      runway: "Well-funded",
      growthRate: "200% YoY",
      lastRound: "Series C (2025)",
      investors: ["Valor Equity", "a16z", "Sequoia"],
    },
    pmf: {
      score: 82,
      nps: 55,
      retention: "120%+ net expansion",
      marketGrowth: "AI models growing 45% CAGR",
      competitivePosition: "Emerging challenger",
      signals: ["Grok models", "X integration", "Colossus compute"],
    },
    packages: {
      score: 82,
      baseSalary: "$140K–$190K",
      ote: "$280K–$380K",
      equity: "Significant equity",
      benefits: ["Full benefits"],
      quota: "$800K–$2M consumption",
      quotaAttainment: "68% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE"],
    gtmTeamSize: "50+",
    expandingRegions: ["US Enterprise"],
  },
  {
    slug: "vercel",
    name: "Vercel",
    website: "https://vercel.com",
    description: "Frontend cloud platform for deploying and scaling web applications.",
    industry: "Developer Tools / Cloud",
    stage: "Series G ($9.3B val)",
    headcount: "600+",
    hq: "San Francisco, CA",
    founded: 2015,
    sellsItself:
      "Next.js creator with AI SDK and v0 — developer community creates enterprise pipeline.",
    categories: ["forbes_ai50", "established"],
    salesMotion: "hybrid",
    compModel: "consumption",
    benchmarks: b(90, 92, 80, 78, 91),
    threeTs: makeThreeTs(92, 84, 80, {
      timing: "Frontend cloud + AI SDK riding developer AI wave",
      territory: "PLG funnel with growing enterprise motion",
      talent: "Developer sales — technical acumen required",
    }),
    financials: {
      score: 90,
      revenue: "$200M+ ARR (est.)",
      funding: "$300M Series G",
      runway: "Well-funded",
      growthRate: "80% YoY",
      lastRound: "Series G (2025)",
      investors: ["Accel", "GV", "GIC"],
    },
    pmf: {
      score: 92,
      nps: 70,
      retention: "135%+ net expansion",
      marketGrowth: "Frontend cloud growing 25% CAGR",
      competitivePosition: "Category leader",
      signals: ["Next.js", "AI SDK", "v0 AI builder"],
    },
    packages: {
      score: 84,
      baseSalary: "$125K–$165K",
      ote: "$250K–$330K",
      equity: "Pre-IPO equity",
      benefits: ["Full benefits"],
      quota: "$500K–$1M consumption",
      quotaAttainment: "78% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Developer Advocate", "Solutions Engineer"],
    gtmTeamSize: "100+",
    expandingRegions: ["US Enterprise", "EMEA"],
  },
];

export const hyperscalerSeeds: CompanySeed[] = [
  {
    slug: "aws",
    name: "AWS",
    website: "https://aws.amazon.com",
    description: "Amazon Web Services — world's largest cloud computing platform.",
    industry: "Cloud / Hyperscaler",
    stage: "Public (AMZN)",
    headcount: "100,000+",
    hq: "Seattle, WA",
    founded: 2006,
    sellsItself:
      "Cloud market leader with AI services — consumption model rewards account expansion.",
    categories: ["hyperscaler"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(85, 90, 88, 65, 95),
    threeTs: makeThreeTs(88, 90, 70, {
      timing: "Cloud + AI workload migration accelerating",
      territory: "Global coverage with dedicated enterprise pods",
      talent: "Mature org, competitive but high ceiling on consumption",
    }),
    financials: {
      score: 98,
      revenue: "$110B+ ARR",
      funding: "Public",
      runway: "N/A (profitable)",
      growthRate: "18% YoY",
      lastRound: "N/A",
      investors: ["Public"],
    },
    pmf: {
      score: 97,
      nps: 60,
      retention: "120%+ net expansion",
      marketGrowth: "Cloud market growing 20% CAGR",
      competitivePosition: "Market leader (32% share)",
      signals: ["Largest cloud", "AI services", "Enterprise dominance"],
    },
    packages: {
      score: 88,
      baseSalary: "$130K–$180K",
      ote: "$260K–$400K",
      equity: "AMZN RSUs",
      benefits: ["Full benefits"],
      quota: "$2M–$10M consumption",
      quotaAttainment: "65% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE", "Solutions Architect"],
    gtmTeamSize: "15,000+",
    expandingRegions: ["APAC", "EMEA", "LATAM", "US Enterprise"],
  },
  {
    slug: "microsoft-azure",
    name: "Microsoft Azure",
    website: "https://azure.microsoft.com",
    description: "Microsoft's cloud computing platform with deep enterprise integration.",
    industry: "Cloud / Hyperscaler",
    stage: "Public (MSFT)",
    headcount: "220,000+",
    hq: "Redmond, WA",
    founded: 2010,
    sellsItself:
      "Enterprise incumbency + OpenAI partnership — Copilot upsell riding existing relationships.",
    categories: ["hyperscaler"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(88, 92, 90, 68, 96),
    threeTs: makeThreeTs(92, 92, 72, {
      timing: "Copilot + Azure AI driving enterprise cloud consolidation",
      territory: "Unmatched enterprise relationships globally",
      talent: "Large org but Copilot creates new greenfield",
    }),
    financials: {
      score: 98,
      revenue: "$75B+ cloud ARR",
      funding: "Public",
      runway: "N/A (profitable)",
      growthRate: "30% YoY",
      lastRound: "N/A",
      investors: ["Public"],
    },
    pmf: {
      score: 96,
      nps: 62,
      retention: "125%+ net expansion",
      marketGrowth: "Cloud market growing 20% CAGR",
      competitivePosition: "#2 cloud (23% share)",
      signals: ["OpenAI partnership", "Copilot", "Enterprise incumbency"],
    },
    packages: {
      score: 90,
      baseSalary: "$140K–$190K",
      ote: "$280K–$420K",
      equity: "MSFT RSUs",
      benefits: ["Full benefits"],
      quota: "$2M–$8M consumption",
      quotaAttainment: "68% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE", "Cloud Solution Architect"],
    gtmTeamSize: "12,000+",
    expandingRegions: ["APAC", "EMEA", "LATAM", "US Enterprise"],
  },
  {
    slug: "google-cloud",
    name: "Google Cloud",
    website: "https://cloud.google.com",
    description: "Google's cloud platform with AI/ML leadership and data analytics.",
    industry: "Cloud / Hyperscaler",
    stage: "Public (GOOGL)",
    headcount: "180,000+",
    hq: "Mountain View, CA",
    founded: 2008,
    sellsItself:
      "AI/ML leadership with Gemini — aggressive enterprise push with consumption incentives.",
    categories: ["hyperscaler"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(86, 88, 85, 62, 93),
    threeTs: makeThreeTs(90, 88, 68, {
      timing: "Gemini + AI workloads driving cloud adoption",
      territory: "Aggressive enterprise investment, global expansion",
      talent: "Competitive comp but quota pressure on consumption",
    }),
    financials: {
      score: 95,
      revenue: "$45B+ ARR",
      funding: "Public",
      runway: "N/A (profitable)",
      growthRate: "28% YoY",
      lastRound: "N/A",
      investors: ["Public"],
    },
    pmf: {
      score: 94,
      nps: 58,
      retention: "120%+ net expansion",
      marketGrowth: "Cloud market growing 20% CAGR",
      competitivePosition: "#3 cloud (11% share)",
      signals: ["Gemini AI", "BigQuery", "Kubernetes origin"],
    },
    packages: {
      score: 88,
      baseSalary: "$135K–$185K",
      ote: "$270K–$400K",
      equity: "GOOGL RSUs",
      benefits: ["Full benefits"],
      quota: "$1.5M–$6M consumption",
      quotaAttainment: "62% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Strategic AE", "Customer Engineer"],
    gtmTeamSize: "8,000+",
    expandingRegions: ["APAC", "EMEA", "LATAM", "US Enterprise"],
  },
  {
    slug: "oracle-cloud",
    name: "Oracle Cloud",
    website: "https://oracle.com/cloud",
    description: "Oracle's cloud infrastructure and applications platform.",
    industry: "Cloud / Hyperscaler",
    stage: "Public (ORCL)",
    headcount: "160,000+",
    hq: "Austin, TX",
    founded: 2016,
    sellsItself:
      "Database incumbency driving cloud migration — aggressive pricing to win enterprise workloads.",
    categories: ["hyperscaler"],
    salesMotion: "enterprise",
    compModel: "consumption",
    benchmarks: b(78, 85, 82, 60, 88),
    threeTs: makeThreeTs(82, 84, 65, {
      timing: "Database migration to cloud accelerating",
      territory: "Strong in existing Oracle accounts globally",
      talent: "Mature org, relationship-selling culture",
    }),
    financials: {
      score: 92,
      revenue: "$15B+ cloud ARR",
      funding: "Public",
      runway: "N/A (profitable)",
      growthRate: "22% YoY",
      lastRound: "N/A",
      investors: ["Public"],
    },
    pmf: {
      score: 90,
      nps: 52,
      retention: "115%+ net expansion",
      marketGrowth: "Cloud market growing 20% CAGR",
      competitivePosition: "#4 cloud (3% share)",
      signals: ["Database dominance", "OCI growth", "Multi-cloud deals"],
    },
    packages: {
      score: 85,
      baseSalary: "$125K–$175K",
      ote: "$250K–$380K",
      equity: "ORCL RSUs",
      benefits: ["Full benefits"],
      quota: "$1M–$5M consumption",
      quotaAttainment: "60% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Cloud AE", "Applications AE"],
    gtmTeamSize: "5,000+",
    expandingRegions: ["APAC", "EMEA", "US Enterprise"],
  },
  {
    slug: "ibm-cloud",
    name: "IBM Cloud",
    website: "https://ibm.com/cloud",
    description: "IBM's hybrid cloud and AI platform including Red Hat and watsonx.",
    industry: "Cloud / Hyperscaler",
    stage: "Public (IBM)",
    headcount: "280,000+",
    hq: "Armonk, NY",
    founded: 2019,
    sellsItself:
      "Hybrid cloud + Red Hat — enterprise incumbency in regulated industries.",
    categories: ["hyperscaler"],
    salesMotion: "enterprise",
    compModel: "hybrid",
    benchmarks: b(72, 80, 85, 58, 85),
    threeTs: makeThreeTs(78, 84, 62, {
      timing: "Hybrid cloud in regulated industries steady",
      territory: "Strong in financial services, government globally",
      talent: "Mature org, relationship-heavy selling",
    }),
    financials: {
      score: 88,
      revenue: "$12B+ cloud ARR",
      funding: "Public",
      runway: "N/A (profitable)",
      growthRate: "12% YoY",
      lastRound: "N/A",
      investors: ["Public"],
    },
    pmf: {
      score: 86,
      nps: 48,
      retention: "110% net expansion",
      marketGrowth: "Hybrid cloud growing 18% CAGR",
      competitivePosition: "Hybrid cloud leader",
      signals: ["Red Hat", "watsonx AI", "Regulated industries"],
    },
    packages: {
      score: 82,
      baseSalary: "$120K–$170K",
      ote: "$240K–$360K",
      equity: "IBM RSUs",
      benefits: ["Full benefits"],
      quota: "$1M–$4M",
      quotaAttainment: "58% of reps hit quota",
    },
    hiringRoles: ["Enterprise AE", "Cloud AE", "Red Hat AE"],
    gtmTeamSize: "4,000+",
    expandingRegions: ["EMEA", "APAC", "US Enterprise"],
  },
];
